language: php
matrix:
  include:
    - php: 7.3
      env: ANALYSIS='true'
before_script:
  - composer require php-coveralls/php-coveralls:^2.1.0
install: composer install -n
script: ./vendor/bin/phpunit -c phpunit.xml
after_success: vendor/bin/php-coveralls -v
